### ISSUE TITLE
[Категории] Запрос на список категорий возвращает не все нужные данные

### ISSUE THREAD

**Issue by Chantreck** [MaximTkachev/SuperDuperQuizBackend#4]
Хотелось бы, чтобы запрос на список категорий возвращал количество викторин на каждую из категорий

**Comment by Chantreck** [comment]
@MaximTkachev сделай, пожалуйста, умоляю

**Comment by MaximTkachev** [comment]
Сделал так, чтобы запросы на категории возвращали еще и количество викторин в ней. Эту версию ты можешь найти в [первом релизе](https://github.com/MaximTkachev/SuperDuperQuizBackend/releases/tag/v1.0.0) или в [ветке main](https://github.com/MaximTkachev/SuperDuperQuizBackend/commit/e5de8dd465aca4aa93b9c23851c789beaf61598f)
